Placeholder comms update
getsolus/solus-site.github.io pull request #52
Opened 2024-11-02 01:34 UTC by BraydenGirard

Wording may need to be updated here and I am unsure what the proper email address should be for the comms team.

2024-11-02 15:19 UTC, davidjharder requested changes
Thanks for the fix-up.
I've created the "comms" address. I prefer a simpler writing style.

2024-11-02 15:19 UTC, davidjharder commented on content/press.html
> +    Reach out to our comms team to inquire about information in regards to our products (remove NOSPAM):
```suggestion
    Reach out to our communications team to ask about our products (remove NOSPAM):
```

2024-11-02 16:19 UTC, davidjharder commented
Looks good! I'll merge this sometime later when I'm back home

2024-11-02 16:19 UTC, davidjharder approved these changes

2024-11-02 20:43 UTC, TraceyC77 commented
@BraydenGirard  Please update the commit message before you merge with
"Fixes #45"

2024-11-04 18:31 UTC, BraydenGirard commented
@TraceyC77 is that what you meant ? I updated this PR name to match. I can not merge though as I do not have write access.

2024-11-04 19:16 UTC, merged